name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  governance-lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Job summary
        run: |
          {
            echo "## Lint summary";
            echo "- cargo fmt --all -- --check";
            echo "- cargo clippy --all-targets --all-features -- -D warnings";
          } >> "$GITHUB_STEP_SUMMARY"

  governance-test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: governance-lint
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run tests
        run: cargo test --all-features
      - name: Job summary
        run: |
          {
            echo "## Test summary";
            echo "- cargo test --all-features";
          } >> "$GITHUB_STEP_SUMMARY"

  governance-build:
    name: Release Build Validation
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs:
      - governance-test
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build release artifacts
        run: cargo build --workspace --release
      - name: Job summary
        run: |
          {
            echo "## Build summary";
            echo "- cargo build --workspace --release";
          } >> "$GITHUB_STEP_SUMMARY"

  governance-security:
    name: Security & Compliance (Placeholder)
    runs-on: ubuntu-latest
    needs:
      - governance-build
    steps:
      - name: Acknowledge pending security automation
        run: |
          echo "Security scanning to be implemented in Issue #18." >> "$GITHUB_STEP_SUMMARY"
